### ISSUE TITLE
Not yet open source

### ISSUE THREAD

**Issue by MrTechGadget** [fotherja/EV_Charger#1]
Can you select a license if you are intending this to be open source? Without a license, we can't use your materials even for private use or contribute to it. 

Thanks, it looks great!

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by fotherja** [comment]
I have added an MIT license.txt file. Is that now ok or does that not work for the non-software files?

**Comment by MrTechGadget** [comment]
Works perfectly and covers the Arduino code as well, thanks again for sharing this solution, I look forward to tinkering with my own!
