### ISSUE TITLE
ADC operation

### ISSUE THREAD

**Issue by bosston88** [fotherja/EV_Charger#2]
First, thanks for your work and for sharing it! I was looking at the code and found something I would like to understand better. Is ADC working in the way, that it reads Pilot voltage once and then GFCI value for 255 times? Then "selector" overflows and repeats?
`// This code runs when the PWM signal is in the middle of its low period
ISR(TIMER1_OVF_vect)
{
  static byte selector = 0;
  if(ADCSRA & 0b01000000)                                                       // If the ADC is still performing a conversion (it shouldn't be) then return
    return;
      
  if(selector && 1)  {
    ADMUX = B01000000;     
    ADCSRA |= B01000000;
    ADC_Channel = 0;    
  } 
  else  {     
    ADMUX = B01000001;
    ADCSRA |= B01000000;
    ADC_Channel = 1;     
  }

  selector++;
}`
I think it violates the standard where you need to "react" to any change from state C within 100ms. Correct me if I'm wrong.

**Comment by fotherja** [comment]
Hello,
Thanks for pointing this out. What I meant to do was a bitwise & so that as the selector variable increments it alternately reads the GFCI ADC channel and then the Pilot voltage before repeating

I suppose I never noticed because 255ms is still pretty quick. I will correct this.

**Comment by bosston88** [comment]
Glad I could help. This could work:
`ISR(TIMER1_OVF_vect)
{
static byte selector = 0;
if(ADCSRA & 0b01000000) // If the ADC is still performing a conversion (it shouldn't be) then return
return;

if(selector) {
ADMUX = B01000000;
ADCSRA |= B01000000;
ADC_Channel = 0;
selector = 0;
}
else {
ADMUX = B01000001;
ADCSRA |= B01000000;
ADC_Channel = 1;
selector = 1;
}
}`

**Comment by fotherja** [comment]
I have now corrected this and tested the new code. Up and running and working. Thank you very much!
