### ISSUE TITLE
Cannot get car to charge

### ISSUE THREAD

**Issue by m1geo** [fotherja/EV_Charger#3]
Hi.

I have copied your circuit part-for-part on your PCB and am having a few issues. Using resistors and a diode on the CP line, I can toggle between state A and state B, but cannot get into state C where charging begins.

If I connect my car (Tesla Model Y Perf) the car requests charging but the contactors never click. The car stops with "Ready to charge, waiting for charger power". The charger UART shows State A going into State B and stopping.

Just wondered where I should look first.

Thanks!

**Comment by fotherja** [comment]
Sounds like the Arduino is not reading the pilot voltages correctly or the pilot voltages are not in spec. 

If it moves from state A to state B then it must be reading the pilot voltage to some extent. Perhaps your resistor values aren't quite right? 

I'd advise outputting the ADC readings over serial so that you can see whether they are appropriate. Let me know how it goes or if you have any other questions

**Comment by m1geo** [comment]
Thanks. I thought as much. I'll tinker with the ADC threshold values - I saw your code for printing out the ADC values. Using that causes the Arduino to reboot, so I added a call to reset the WDT into the loop. 

**Do you know what test resistor values I should be using to switch between each state?** 

I'm using a simple 1N4148 in series with fixed through-hole resistors to simulate the car while testing. I see the same situation when using fixed resistors; State A > State B, but never any further. The Arduino ignores my attempt for a transition between State B onwards. Messing with the value too much results in a fault (understandable) but I cannot get things to work as I had hoped. I'm pretty sure I have used the correct resistors.

**Comment by fotherja** [comment]
Good stuff re. Adding WDT reset into the loop.

In order to proceed from state B to state C the GFCI test needs to be successful. Is that holding things up?

A 900 ohm resistor and diode to ground should be about right.

**Comment by m1geo** [comment]
Great, thanks. No, I have the RCD (GFCI) test working OK using a cheap transformer. I added 5 turns of wire to it to inject a fault current. Passes the test in around ~20ms (from my memory).

Nice project. Thanks.
