### ISSUE TITLE
GFCI transformer P/N not specified

### ISSUE THREAD

**Issue by m1geo** [fotherja/EV_Charger#4]
I couldn't see where you specify a part number for the transformer. Do you have a recommended part from AliExpress, eBay, etc.

Thanks!

**Comment by setters** [comment]
Hello. Hopefully you are getting answers.
I'm not sure why I am getting the messages in my inbox. Maybe I follow this
project on GitHub but I don't know the details of it.

**Comment by m1geo** [comment]
Make sure your "Watch" setting is appropriately set; i.e., not "all activity". Github help will have more instructions on how to set things up.

My question was aimed at @fotherja :)

**Comment by fotherja** [comment]
Hello, yes, I got the GFCI from the EVSE store. Here's the link: https://store.openevse.com/collections/all-products/products/gfci-current-transformer

**Comment by m1geo** [comment]
Eeesh, you're right, I did see those and immediately dismissed them as being far too expensive.

I've opted for a similar part: https://www.aliexpress.com/item/1005004279553697.html and will self-wind a test coil. This part is <£1 GBP.

Closing this ticket! Thanks for the answer.
